from pdf_generator import crear_pdf
import tkinter as tk


def test_crear_pdf():
    root = tk.Tk()
    # Crear un entry para cada entrada
    fecha_entry = tk.Entry(root)
    nombre_apellido_entry = tk.Entry(root)
    edad_entry = tk.Entry(root)
    sexo_entry = tk.Entry(root)
    fecha_nacimiento_entry = tk.Entry(root)
    nacionalidad_entry = tk.Entry(root)
    ocupacion_entry = tk.Entry(root)
    estado_civil_entry = tk.Entry(root)
    dni_entry = tk.Entry(root)
    cel_fijo_entry = tk.Entry(root)
    obra_social_entry = tk.Entry(root)
    afiliado_entry = tk.Entry(root)
    direccion_entry = tk.Entry(root)
    comparte_viviendo_entry = tk.Entry(root)
    email_entry = tk.Entry(root)
    familiar_contacto_entry = tk.Entry(root)
    motivo_consulta_entry = tk.Entry(root)
    tiempo_evolucion_entry = tk.Entry(root)
    antecedentes_enfermedad_entry = tk.Entry(root)
    medico_cabecera_entry = tk.Entry(root)
    elementos_asistencia_entry = tk.Entry(root)
    estudios_complementarios_entry = tk.Entry(root)
    cirugias_entry = tk.Entry(root)
    medicacion_entry = tk.Entry(root)
    kinesiologia_entry = tk.Entry(root)
    fonoaudiologia_entry = tk.Entry(root)
    psicologia_entry = tk.Entry(root)
    terapia_ocupacional_entry = tk.Entry(root)
    opiniones_objetivos_entry = tk.Entry(root)

    # Insertar un valor por defecto en cada entrada
    fecha_entry.insert(0, "01/01/2025")
    nombre_apellido_entry.insert(0, "Test")
    edad_entry.insert(0, "30")
    sexo_entry.insert(0, "Masculino")
    fecha_nacimiento_entry.insert(0, "01/01/1995")
    nacionalidad_entry.insert(0, "Argentina")
    ocupacion_entry.insert(0, "Tester")
    estado_civil_entry.insert(0, "Soltero")
    dni_entry.insert(0, "12345678")
    cel_fijo_entry.insert(0, "1234567890")
    obra_social_entry.insert(0, "Osde")
    afiliado_entry.insert(0, "123456")
    direccion_entry.insert(0, "Calle Falsa 123")
    comparte_viviendo_entry.insert(0, "Solo")
    email_entry.insert(0, "test@test.com")
    familiar_contacto_entry.insert(0, "Familiar")
    motivo_consulta_entry.insert(0, "Consulta")
    tiempo_evolucion_entry.insert(0, "1 semana")
    antecedentes_enfermedad_entry.insert(0, "Ninguno")
    medico_cabecera_entry.insert(0, "Dr. Test")
    elementos_asistencia_entry.insert(0, "Ninguno")
    estudios_complementarios_entry.insert(0, "Ninguno")
    cirugias_entry.insert(0, "Ninguna")
    medicacion_entry.insert(0, "Ninguna")
    kinesiologia_entry.insert(0, "Ninguna")
    fonoaudiologia_entry.insert(0, "Ninguna")
    psicologia_entry.insert(0, "Ninguna")
    terapia_ocupacional_entry.insert(0, "Ninguna")
    opiniones_objetivos_entry.insert(0, "Ninguna")

    crear_pdf(fecha_entry, nombre_apellido_entry, edad_entry, sexo_entry, fecha_nacimiento_entry, nacionalidad_entry, ocupacion_entry, estado_civil_entry, dni_entry, cel_fijo_entry, obra_social_entry, afiliado_entry, direccion_entry, comparte_viviendo_entry, email_entry, familiar_contacto_entry,
              motivo_consulta_entry, tiempo_evolucion_entry, antecedentes_enfermedad_entry, medico_cabecera_entry, elementos_asistencia_entry, estudios_complementarios_entry, cirugias_entry, medicacion_entry, kinesiologia_entry, fonoaudiologia_entry, psicologia_entry, terapia_ocupacional_entry, opiniones_objetivos_entry)
    root.destroy()
